In [1]:
import pandas as pd
import numpy as np

In [2]:
import xgboost

In [3]:
import psycopg2

In [4]:
def main():
	#Define our connection string
	conn_string = "host='localhost' dbname='my_database' user='postgres' password='password'"

	# print the connection string we will use to connect
	print "Connecting to database\n	->%s" % (conn_string)

	# get a connection, if a connect cannot be made an exception will be raised here
	conn = psycopg2.connect(conn_string)

	# conn.cursor will return a cursor object, you can use this cursor to perform queries
	cursor = conn.cursor()
	print "Connected!\n"

if __name__ == "__main__":
	main()

SyntaxError: invalid syntax (166791105.py, line 6)

In [4]:
conn_string = "host='db' dbname='postgres' user='postgres' password='password'"

In [6]:
conn = psycopg2.connect(conn_string)

In [7]:
psycopg2.__version__

'2.9.3 (dt dec pq3 ext lo64)'

In [8]:
psycopg2.__libpq_version__

120011

In [9]:
# conn.cursor will return a cursor object, you can use this cursor to perform queries
cursor = conn.cursor()

# execute our Query
cursor.execute("SELECT * FROM my_table")

UndefinedTable: relation "my_table" does not exist
LINE 1: SELECT * FROM my_table
                      ^

In [10]:
df = pd.read_csv('wine.data')
df.head()

,1,14.23,1.71,2.43,15.6,127,2.8,3.06,.28,2.29,5.64,1.04,3.92,1065
0,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
1,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
2,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
3,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
4,1,14.20,1.76,2.45,15.2,112,3.27,3.39,0.34,1.97,6.75,1.05,2.85,1450

In [6]:
from sqlalchemy import create_engine
engine = create_engine('postgresql://postgres:password@db:5432/postgres')

In [16]:
#curs = conn.cursor()
#curs.execute("ROLLBACK")
conn.commit()

In [12]:
cursor.execute('drop table wine')
conn.commit()

InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block

In [17]:
curs.execute("commit")
conn.commit()

In [18]:
df.to_sql('wine', engine)

177

In [7]:
df_pg = pd.read_sql_query('select * from wine', con=engine)

In [8]:
df_pg.head()

,index,1,14.23,1.71,2.43,15.6,127,2.8,3.06,.28,2.29,5.64,1.04,3.92,1065
0,0,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
1,1,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
2,2,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
3,3,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
4,4,1,14.20,1.76,2.45,15.2,112,3.27,3.39,0.34,1.97,6.75,1.05,2.85,1450